"""Persistence facade. All state paths remain rooted at the repository root."""
from .production_core import (
    PROJECT_ROOT,
    REGISTRY_FILE,
    PAYMENTS_FILE,
    SESSIONS_FILE,
    ACTUALS_FILE,
    ALERT_STATE_FILE,
    TELEGRAM_UPDATE_STATE_FILE,
    TELEGRAM_DAEMON_LOCK_FILE,
    TACTICAL_STATE_FILE,
    _supabase_enabled,
    _supabase_headers,
    _supabase_state_url,
    _supabase_load_state,
    _supabase_save_state,
    _read_local_json,
    _write_local_json_atomic,
    _load_persistent_state,
    _save_persistent_state,
    get_persistence_status,
    load_actuals_cache,
    save_actuals_cache,
    load_sessions_cache,
    save_sessions_cache,
    load_vip_registry,
    save_vip_registry,
)
