"""Architecture B2 -- the single, frozen registry of voting families.

This module is the ONE place where the voting budget lives. If a family is not
declared here it cannot vote, because every aggregation path in this package
takes its family definitions from ``VOTING_FAMILIES``.

Three registries are maintained, and they are deliberately disjoint:

``VOTING_FAMILIES``
    The fixed voting core. Adding a family here is a budget event and requires
    written justification in the definition itself.

``DORMANT_COMPONENTS``
    Documented, not computed, because the data to support them does not exist
    in this project. They are declared rather than omitted so that their
    absence is *visible* -- an unavailable family reduces Data Confidence
    instead of silently vanishing.

``WITHHELD_COMPONENTS``
    Code for these exists in the project but must NOT be activated yet, for a
    recorded safety reason. This encodes the operator's Stage A safety
    requirements structurally rather than as a comment someone can forget.

The budget of ~6 is an architectural complexity constraint, not a proven
number. Its purpose is to stop factor proliferation: adding an indicator to an
existing family is routine, adding a family is not.
"""
from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Mapping

from .enums import Horizon, Role
from .horizons import SeriesFrequency

#: Maximum number of independent voting families across the entire architecture.
VOTING_BUDGET = 6


class MemberScale(Enum):
    """The numeric scale a member signal actually lives on.

    A flat/neutral threshold is only meaningful relative to a scale, and this
    project holds members on two genuinely different ones. Declaring the scale
    is what stops a threshold chosen for one from being applied to the other --
    which is exactly the defect this enum was introduced to close.

    ``BOUNDED_UNIT``
        A score already squashed onto [-1, 1], where 1.0 is the maximum the
        producing function can emit. Every ``calc_mtf`` score and every rescaled
        news-points reading is of this kind. Here "0.05" means five percent of
        full scale, which is the sense the existing project convention intended.

    ``STANDARDISED_SIGMA``
        A z-score: an observation divided by its own noise scale, unbounded, and
        where 1.0 means "a one-standard-deviation move" rather than "the maximum
        possible". A threshold of 0.05 on this scale means five hundredths of a
        standard deviation, which is noise, not evidence.

    ``CATEGORICAL_UNIT``
        A member that only ever emits an exact member of {-1.0, 0.0, +1.0}.
        Any threshold strictly between 0 and 1 behaves identically.
    """

    BOUNDED_UNIT = "bounded_unit"
    STANDARDISED_SIGMA = "standardised_sigma"
    CATEGORICAL_UNIT = "categorical_unit"


#: Neutral band for a member on the BOUNDED_UNIT scale.
#:
#: NOT a new number: this is the 0.05 "flat vote" cutoff the project already
#: uses in ``_gold_evidence_conflict_diagnostics``, retained unchanged for the
#: scale it was actually chosen for.
BOUNDED_UNIT_FLAT_THRESHOLD = 0.05

#: Neutral band for a member on the STANDARDISED_SIGMA scale, in sigma.
#:
#: NOT a new number either, and deliberately not tuned. It is
#: ``ValidationConfig.neutral_band_atr_multiple`` -- the k the validation layer
#: already uses, with the same sqrt-time scaling, to decide whether a REALISED
#: move escaped the noise band and may therefore carry a verdict.
#:
#: Using one k on both sides is a coherence requirement rather than a
#: preference. If the validation layer would score a 0.4-sigma outcome as
#: NEUTRAL -- "the market did not go anywhere" -- then the evidence layer must
#: not read a 0.4-sigma input as directional and claim the market is going
#: somewhere. The two halves of the system have to agree about what counts as
#: noise, or a claim can be generated by evidence its own resolution would
#: refuse to score.
#:
#: This is a NOISE FLOOR, not a calibration. It is deliberately the smallest
#: value with an existing justification in this repository, and it is left
#: injectable so the null benchmark can vary it as a research control. Raising
#: it because it improves a hit rate would be calibration, which is withheld.
STANDARDISED_SIGMA_FLAT_THRESHOLD = 0.5

#: Neutral band for CATEGORICAL_UNIT members. Any value in (0, 1) is
#: equivalent; the bounded-unit constant is reused rather than adding a third.
CATEGORICAL_UNIT_FLAT_THRESHOLD = BOUNDED_UNIT_FLAT_THRESHOLD

_DEFAULT_THRESHOLD_BY_SCALE: Mapping[MemberScale, float] = {
    MemberScale.BOUNDED_UNIT: BOUNDED_UNIT_FLAT_THRESHOLD,
    MemberScale.STANDARDISED_SIGMA: STANDARDISED_SIGMA_FLAT_THRESHOLD,
    MemberScale.CATEGORICAL_UNIT: CATEGORICAL_UNIT_FLAT_THRESHOLD,
}


class EvidenceExpectation(Enum):
    """Whether the architecture EXPECTS this member to carry evidence.

    This is the H3 mechanism. Data Confidence previously asked only "did this
    family speak?", which is a boolean over five families and is satisfied by a
    single surviving member. It could therefore report HIGH with five of fifteen
    declared member signals present. Coverage needs a denominator, and a
    denominator is only meaningful once each member declares whether its absence
    is a data deficiency at all.

    The classes are CATEGORICAL on purpose. A numeric importance weight would be
    an uncalibrated free parameter chosen before the corpus that could justify
    it exists -- the same objection that keeps ``ConfidenceLevel`` categorical.

    ``REQUIRED``
        Absence makes the evaluation uninformative. Counted in the denominator.
        **No production member currently declares this**: "required" is already
        expressed at family granularity by ``CRITICAL_FAMILY_KEYS``, and
        duplicating that policy at member level is not a change H3 was approved
        to make. It is declared here because the taxonomy is incomplete without
        it and because a future family may genuinely need it. Note that it does
        NOT create a path to LOW -- see ``EXPECTED`` below.

    ``EXPECTED``
        Should normally arrive; its absence is a real degradation of coverage.
        Counted in the denominator.

        REQUIRED and EXPECTED are treated identically by the coverage ratio.
        That is deliberate: H3 is bound by invariant I-1, which forbids any new
        route to ``ConfidenceLevel.LOW``. The only conditions that may reach LOW
        are the pre-existing ones (a critical family unavailable, two or more
        families unavailable, a BROKEN series). Coverage floors at MODERATE, so
        a REQUIRED member that is missing degrades coverage and is named in the
        provenance block, but it cannot by itself degrade the decision.

    ``OPTIONAL``
        Its absence is not a data deficiency. Excluded from the denominator
        entirely, so it can neither raise nor lower coverage.

    ``UNOBTAINABLE``
        Declared, and never obtainable in this project. Excluded from the
        denominator. Without this class the two permanently-null Structure
        members would cap every record ever written, which is a constant offset
        carrying no information rather than a measurement. A member declaring
        this MUST record why in ``frequency_basis``; the validator enforces it.
    """

    REQUIRED = "required"
    EXPECTED = "expected"
    OPTIONAL = "optional"
    UNOBTAINABLE = "unobtainable"

    @property
    def is_counted(self) -> bool:
        """True when this member belongs in the coverage denominator."""
        return self in (EvidenceExpectation.REQUIRED, EvidenceExpectation.EXPECTED)


#: Bumped when the MEANING of an expectation assignment changes -- a member
#: reclassified, a class redefined, a new class added. Stored on every record
#: alongside the coverage basis so a historical Data Confidence value stays
#: explicable if these declarations are ever revised.
EXPECTATION_VERSION = "b2-evidence-expectation-v1"


@dataclass(frozen=True)
class MemberSpec:
    """What one family member IS, as opposed to what it read this evaluation.

    Three facts live here and all three are structural rather than incidental:

    *   ``scale`` + ``flat_threshold`` -- the neutral band, expressed in the
        member's own units. Without this a single package constant gets applied
        to quantities that do not share a scale.
    *   ``frequency`` -- the natural publication cadence of the slowest series
        behind the member. This is what ``horizons.horizon_compatible`` needs in
        order to refuse a member that is too slow to be evidence at a given
        decision horizon.
    *   ``expectation`` -- whether the absence of this member is a data
        deficiency. This is what gives the H3 coverage ratio a denominator that
        is DECLARED rather than discovered from whatever happened to arrive.

    ``frequency`` is deliberately the SLOWEST constituent series, not an
    average. A member blended from a monthly and a quarterly release cannot
    update faster than its quarterly leg, and treating it as though it could is
    the frequency smuggling this field exists to prevent.

    ``expectation`` defaults to ``EXPECTED``, which keeps every pre-H3
    construction of this dataclass valid -- including
    ``dataclasses.replace(spec, flat_threshold=...)`` in the null benchmark --
    and defaults in the direction that COUNTS a member rather than silently
    excusing it.
    """

    key: str
    scale: MemberScale
    frequency: SeriesFrequency
    #: Source note recording where ``frequency`` came from, so a later reader
    #: can check it against the production series configuration rather than
    #: trusting it.
    frequency_basis: str = ""
    flat_threshold: float | None = None
    #: Whether the architecture expects evidence here. See EvidenceExpectation.
    expectation: EvidenceExpectation = EvidenceExpectation.EXPECTED

    @property
    def threshold(self) -> float:
        """The neutral band for this member, defaulted from its scale."""
        if self.flat_threshold is not None:
            return float(self.flat_threshold)
        return _DEFAULT_THRESHOLD_BY_SCALE[self.scale]

    def as_record(self) -> dict[str, object]:
        return {
            "member": self.key,
            "scale": self.scale.value,
            "frequency": self.frequency.label,
            "frequency_period_days": float(self.frequency.period_days),
            "flat_threshold": float(self.threshold),
            "frequency_basis": self.frequency_basis,
            # H3: the declared expectation, so a stored Data Confidence value
            # can be re-derived without consulting repository history.
            "expectation": self.expectation.value,
        }


@dataclass(frozen=True)
class FamilyDefinition:
    """A voting family. Membership is frozen and must not be tuned against results."""

    key: str
    label: str
    role: Role
    horizon: Horizon
    members: tuple[str, ...]
    justification: str
    data_sources: tuple[str, ...]
    #: One spec per declared member, in the same order. Carries the member's
    #: scale, its neutral band and the cadence of the slowest series behind it.
    #: Required: a member with no declared scale cannot be classified safely,
    #: and a member with no declared frequency cannot be horizon-checked.
    member_specs: tuple[MemberSpec, ...] = ()

    def __post_init__(self) -> None:
        if self.role is not Role.ACTIVE_VOTING:
            raise ValueError(f"{self.key}: a voting family must have role ACTIVE_VOTING")
        if not self.members:
            raise ValueError(f"{self.key}: a voting family must declare at least one member")
        if len(set(self.members)) != len(self.members):
            raise ValueError(f"{self.key}: duplicate member keys")
        spec_keys = tuple(s.key for s in self.member_specs)
        if spec_keys != self.members:
            raise ValueError(
                f"{self.key}: member_specs {list(spec_keys)} must cover exactly the "
                f"declared members {list(self.members)}, in the same order. A member "
                "with no declared scale and frequency cannot be classified or "
                "horizon-checked, and silently defaulting either one is how a "
                "threshold meant for another scale gets applied."
            )

    def spec_for(self, member: str) -> MemberSpec | None:
        for spec in self.member_specs:
            if spec.key == member:
                return spec
        return None


@dataclass(frozen=True)
class InactiveComponent:
    """A component that is declared but not computed."""

    key: str
    label: str
    role: Role
    reason: str
    blocking_requirement: str = ""


@dataclass(frozen=True)
class AssetModuleComponent:
    """An asset-specific transmission module.

    Registered so its role is explicit and enforceable. An asset module is
    ACTIVE NON-VOTING: it computes and conditions interpretation but never
    contributes independent directional evidence, and it does not receive
    voting power until incremental value over the universal core alone has been
    demonstrated -- which no validation has yet done.
    """

    key: str
    label: str
    instrument: str
    role: Role
    rationale: str

    def __post_init__(self) -> None:
        if self.role is not Role.ASSET_SPECIFIC_MODULE:
            raise ValueError(
                f"{self.key}: an asset module must have role ASSET_SPECIFIC_MODULE"
            )


# ---------------------------------------------------------------------------
# THE VOTING CORE -- 5 families, within the budget of ~6.
#
# Only Policy / Real Rates maps onto the canonical B2 macro family list; the
# other three canonical macro families (Liquidity / Funding, Positioning /
# Crowding, Fiscal / Issuance) have no data in this project and are declared
# dormant below rather than faked. Macro Activity and News / Geopolitical are
# declared here because they are the evidence that actually drives every live
# score in this system -- excluding them would produce a voting core that does
# not describe the running platform.
# ---------------------------------------------------------------------------

POLICY_REAL_RATES = FamilyDefinition(
    key="policy_real_rates",
    label="Policy / Real Rates",
    role=Role.ACTIVE_VOTING,
    horizon=Horizon.TACTICAL,
    members=(
        "policy_rate_momentum",
        "real_yield_momentum",
        "nominal_yield_momentum",
        "inflation_expectations_momentum",
    ),
    member_specs=(
        MemberSpec(
            key="policy_rate_momentum",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.BOUNDED_UNIT,
            frequency=SeriesFrequency.MONTHLY,
            frequency_basis=(
                "CURRENCY_SERIES cat='rate' -> FEDFUNDS / ECBDFR / BOERUKM etc, "
                "all monthly-average policy rate series on FRED."
            ),
        ),
        MemberSpec(
            key="real_yield_momentum",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.BOUNDED_UNIT,
            frequency=SeriesFrequency.DAILY,
            frequency_basis="GOLD_SERIES real_yield = DFII10, a daily constant-maturity series.",
        ),
        MemberSpec(
            key="nominal_yield_momentum",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.BOUNDED_UNIT,
            frequency=SeriesFrequency.DAILY,
            frequency_basis="GOLD_SERIES yield = DGS10, a daily constant-maturity series.",
        ),
        MemberSpec(
            key="inflation_expectations_momentum",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.BOUNDED_UNIT,
            frequency=SeriesFrequency.DAILY,
            frequency_basis="GOLD_SERIES inflation_exp = T10YIE, a daily breakeven series.",
        ),
    ),
    justification=(
        "Canonical B2 macro family. Central-bank reaction function, policy "
        "expectations and the real-rate environment. These four members are "
        "one causal source read four ways, so they raise family strength and "
        "never the contribution count."
    ),
    data_sources=(
        "CURRENCY_SERIES indicators with cat='rate' (FEDFUNDS, ECBDFR, BOERUKM, ...)",
        "GOLD_SERIES real_yield (DFII10)",
        "GOLD_SERIES yield (DGS10)",
        "GOLD_SERIES inflation_exp (T10YIE)",
    ),
)

MACRO_ACTIVITY = FamilyDefinition(
    key="macro_activity",
    label="Macro Activity (Inflation / Labour / Growth)",
    role=Role.ACTIVE_VOTING,
    horizon=Horizon.TACTICAL,
    members=(
        "inflation_momentum",
        "labor_momentum",
        "growth_momentum",
    ),
    member_specs=(
        MemberSpec(
            key="inflation_momentum",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.BOUNDED_UNIT,
            frequency=SeriesFrequency.MONTHLY,
            frequency_basis=(
                "CURRENCY_SERIES cat='inflation' -> CPIAUCSL, CPILFESL, PPIFIS, "
                "PPIFES, PCEPILFE, PCEPI. Every one is a monthly release."
            ),
        ),
        MemberSpec(
            key="labor_momentum",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.BOUNDED_UNIT,
            frequency=SeriesFrequency.MONTHLY,
            frequency_basis=(
                "CURRENCY_SERIES cat in {'labor_pos','labor_neg'} -> PAYEMS, "
                "UNRATE and their per-currency equivalents. Monthly releases."
            ),
        ),
        MemberSpec(
            key="growth_momentum",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.BOUNDED_UNIT,
            frequency=SeriesFrequency.QUARTERLY,
            frequency_basis=(
                "CURRENCY_SERIES cat='growth' blends monthly retail sales (RSAFS) "
                "with QUARTERLY GDP. The member is declared at its SLOWEST leg: a "
                "blend cannot update faster than its slowest constituent, and "
                "calling it monthly would be exactly the frequency smuggling "
                "horizons.assert_horizon_compatible exists to refuse."
            ),
        ),
    ),
    justification=(
        "BUDGET EVENT -- justified in writing, approved before implementation. "
        "This is not a new invention: it is the dominant content of the "
        "existing per-currency macro_score. It is economically distinct from "
        "Policy / Real Rates, which prices the reaction function, whereas this "
        "family measures the data flow that function responds to. Splitting "
        "inflation, labour and growth into three families would be the double "
        "count; holding them as one family whose internal agreement raises "
        "strength only is the anti-double-counting treatment."
    ),
    data_sources=(
        "CURRENCY_SERIES indicators with cat in {'inflation','labor_pos','labor_neg','growth'}",
    ),
)

NEWS_GEOPOLITICAL = FamilyDefinition(
    key="news_geopolitical",
    label="News / Geopolitical",
    role=Role.ACTIVE_VOTING,
    horizon=Horizon.TACTICAL,
    members=(
        "rule_based_news",
        "ai_news",
    ),
    member_specs=(
        MemberSpec(
            key="rule_based_news",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.BOUNDED_UNIT,
            frequency=SeriesFrequency.EVENT,
            frequency_basis=(
                "Scraped wires / Telegram / RSS. News has no publication cadence "
                "to be overdue against, so it is EVENT frequency and is usable at "
                "every horizon -- see horizons.assert_horizon_compatible, which "
                "returns early for EVENT rather than comparing periods."
            ),
        ),
        MemberSpec(
            key="ai_news",
            expectation=EvidenceExpectation.OPTIONAL,
            scale=MemberScale.BOUNDED_UNIT,
            frequency=SeriesFrequency.EVENT,
            frequency_basis="Same articles as rule_based_news, scored by the shared AI batch.",
        ),
    ),
    justification=(
        "BUDGET EVENT -- justified in writing, approved before implementation. "
        "News sentiment is 50% of every currency score, 50% of Gold's base, "
        "40% of Oil's and 25% of Nasdaq's in the live system, and it is "
        "independently sourced (scraped wires / Telegram / RSS) rather than "
        "derived from any FRED series. Its two members read the SAME articles, "
        "so they are correlated by construction -- which is precisely why they "
        "belong in one family rather than voting separately."
    ),
    data_sources=(
        "analyze_news_rule_based -> per-asset rule points",
        "shared background AI batch -> per-asset score x confidence",
    ),
)

DIRECTIONAL = FamilyDefinition(
    key="directional",
    label="Directional (Trend / Momentum / Multi-Timeframe)",
    role=Role.ACTIVE_VOTING,
    horizon=Horizon.EXECUTION,
    members=(
        "short_horizon_return",
        "medium_horizon_return",
        "multi_timeframe_alignment",
    ),
    member_specs=(
        MemberSpec(
            key="short_horizon_return",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.STANDARDISED_SIGMA,
            frequency=SeriesFrequency.INTRADAY,
            frequency_basis="compute_tactical_move ret_15m, from the 5-minute bar series.",
        ),
        MemberSpec(
            key="medium_horizon_return",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.STANDARDISED_SIGMA,
            frequency=SeriesFrequency.INTRADAY,
            frequency_basis="compute_tactical_move ret_1h, from the 5-minute bar series.",
        ),
        MemberSpec(
            key="multi_timeframe_alignment",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.CATEGORICAL_UNIT,
            frequency=SeriesFrequency.INTRADAY,
            frequency_basis=(
                "Derived from ret_15m / ret_1h / ret_4h, all from the same "
                "5-minute bar series."
            ),
        ),
    ),
    justification=(
        "Canonical B2 technical family. Trend, momentum and multi-timeframe "
        "alignment agreeing is ONE strong confirmation, not three votes. The "
        "alignment member is derived from the same returns as the other two, "
        "which is exactly the correlation this family structure exists to "
        "absorb."
    ),
    data_sources=("compute_tactical_move -> ret_15m / ret_1h / ret_4h",),
)

STRUCTURE = FamilyDefinition(
    key="structure",
    label="Structure (Price Structure / Breakout / Retest)",
    role=Role.ACTIVE_VOTING,
    horizon=Horizon.EXECUTION,
    members=(
        "breakout_quality",
        "price_structure_zone",
        "retest_behaviour",
    ),
    member_specs=(
        MemberSpec(
            key="breakout_quality",
            expectation=EvidenceExpectation.EXPECTED,
            scale=MemberScale.CATEGORICAL_UNIT,
            frequency=SeriesFrequency.INTRADAY,
            frequency_basis=(
                "compute_tactical_move structure label, classified from closes, "
                "EMAs and prior highs/lows on the 5-minute bar series."
            ),
        ),
        MemberSpec(
            key="price_structure_zone",
            expectation=EvidenceExpectation.UNOBTAINABLE,
            scale=MemberScale.CATEGORICAL_UNIT,
            frequency=SeriesFrequency.INTRADAY,
            frequency_basis=(
                "Structurally Unavailable in this project (macro-conditioned "
                "source); the spec records what it WOULD be if it were ever "
                "sourced from price alone."
            ),
        ),
        MemberSpec(
            key="retest_behaviour",
            expectation=EvidenceExpectation.UNOBTAINABLE,
            scale=MemberScale.CATEGORICAL_UNIT,
            frequency=SeriesFrequency.INTRADAY,
            frequency_basis="Not computed anywhere in this project; see adapters.UNAVAILABLE_REASONS.",
        ),
    ),
    justification=(
        "Canonical B2 technical family. Retest is modelled as a property of a "
        "breakout, not a standalone rule. Two of the three members are "
        "currently Unavailable in this project (see adapters.structure_signals) "
        "and are reported as such rather than defaulted to flat."
    ),
    data_sources=("compute_tactical_move -> structure (breakout/breakdown classification)",),
)

VOTING_FAMILIES: tuple[FamilyDefinition, ...] = (
    POLICY_REAL_RATES,
    MACRO_ACTIVITY,
    NEWS_GEOPOLITICAL,
    DIRECTIONAL,
    STRUCTURE,
)

FAMILIES_BY_KEY: Mapping[str, FamilyDefinition] = {f.key: f for f in VOTING_FAMILIES}

#: Families whose absence should cap total confidence rather than pass quietly.
#: A thesis built with no policy read and no activity read is not a weak thesis,
#: it is an uninformed one.
CRITICAL_FAMILY_KEYS: frozenset[str] = frozenset({"policy_real_rates", "macro_activity"})

#: The canonical universal macro family set, named once here rather than left in
#: the prose comment above ``POLICY_REAL_RATES``.
#:
#: This is the H3 ARCHITECTURAL COMPLETENESS denominator, and it is deliberately
#: NOT "everything in DORMANT_COMPONENTS". Most dormant entries are instrument
#: diagnostics, display artefacts or data-vintage caveats; treating them as
#: missing macro evidence would be arbitrary. These four are the family set the
#: architecture claims to reason over, so their absence -- and only theirs -- is
#: a statement about the completeness of the macro evidence base itself.
#:
#: Exactly one of the four is live here. The other three are declared dormant
#: below because this project holds no funding, positioning or issuance data.
CANONICAL_MACRO_FAMILY_KEYS: frozenset[str] = frozenset(
    {
        "policy_real_rates",
        "liquidity_funding",
        "positioning_crowding",
        "fiscal_issuance",
    }
)

MACRO_FAMILY_KEYS: frozenset[str] = frozenset(
    f.key for f in VOTING_FAMILIES if f.horizon is Horizon.TACTICAL
)
TECHNICAL_FAMILY_KEYS: frozenset[str] = frozenset(
    f.key for f in VOTING_FAMILIES if f.horizon is Horizon.EXECUTION
)


# ---------------------------------------------------------------------------
# ACTIVE NON-VOTING -- implemented analytical state that can condition or
# diagnose a thesis but can never contribute an independent directional vote.
# ---------------------------------------------------------------------------

ACTIVE_NON_VOTING_COMPONENTS: tuple[InactiveComponent, ...] = (
    InactiveComponent(
        key="regime_state",
        label="Regime State",
        role=Role.META_STATE,
        reason=(
            "Implemented in apex.b2.regime and WIRED: classify_regime is called "
            "on every evaluation and its state reaches every shadow record. It "
            "carries no direction field, is never passed to the aggregator, and "
            "conditions interpretation only. This is what an active non-voting "
            "component looks like -- it produces a field in the record."
        ),
    ),
)


# ---------------------------------------------------------------------------
# THE WIRING RULE
#
# The test every entry above has to pass is stated once, here, because this
# registry previously applied it to some components and not to others:
#
#     Code existing is not a capability. A component is ACTIVE only if a live
#     evaluation path calls it AND its result reaches a record. If nothing
#     calls it, or it computes but is never persisted, it is WITHHELD --
#     however good the implementation is.
#
# That is the same sentence already used to withhold relative_value_layer and
# recent_macro_surprise. Applying it consistently moved two components OUT of
# ACTIVE_NON_VOTING at the pre-freeze audit: macro_thesis_invalidation and the
# transmission-confirmation channel of regime confidence. Both are implemented
# well; neither runs. They are recorded below with what would wire them.
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# DORMANT -- documented, not computed, because the data does not exist here.
# Verified by exhaustive search of the project during Phase 1-3 inspection.
# ---------------------------------------------------------------------------

DORMANT_COMPONENTS: tuple[InactiveComponent, ...] = (
    InactiveComponent(
        key="liquidity_funding",
        label="Liquidity / Funding",
        role=Role.DORMANT,
        reason=(
            "No liquidity or funding data exists in this project. Searched and "
            "found nothing for SOFR, repo, OIS, TED, WALCL, RRPONTSYD, NFCI, "
            "STLFSI or credit spreads."
        ),
        blocking_requirement="A funding/liquidity data source must be added and verified.",
    ),
    InactiveComponent(
        key="positioning_crowding",
        label="Positioning / Crowding",
        role=Role.DORMANT,
        reason="No COT, open interest or positioning feed exists in this project.",
        blocking_requirement="A legitimate positioning data source must be added.",
    ),
    InactiveComponent(
        key="fiscal_issuance",
        label="Fiscal / Issuance",
        role=Role.DORMANT,
        reason="No issuance, refunding or auction data exists in this project.",
        blocking_requirement="A sovereign issuance/refunding data source must be added.",
    ),
    InactiveComponent(
        key="financial_cycle",
        label="Financial Cycle",
        role=Role.DORMANT,
        reason=(
            "No credit-to-GDP, system leverage or property-price series exists. "
            "Note that even with data this would be a structural prior that is "
            "unlikely to be validated in any realistic shadow window -- and "
            "'never disproved' must not later be read as 'validated'."
        ),
        blocking_requirement="Quarterly structural leverage data with publication-lag handling.",
    ),
    InactiveComponent(
        key="sovereign_refinancing",
        label="Sovereign Debt / Refinancing",
        role=Role.DORMANT,
        reason=(
            "No sovereign maturity schedule data exists. It also fails the "
            "'what decision does it change?' test in this project as it stands, "
            "so it is not built."
        ),
        blocking_requirement="Sovereign maturity/refunding calendar; and it belongs INSIDE "
                             "Fiscal / Issuance, never as a parallel family.",
    ),
    InactiveComponent(
        key="corporate_maturity_wall",
        label="Corporate Maturity Wall",
        role=Role.DORMANT,
        reason="No corporate refinancing data exists and none may be invented.",
        blocking_requirement="A reliable corporate maturity dataset.",
    ),
    InactiveComponent(
        key="systemic_risk_buildup",
        label="Systemic Risk Build-up",
        role=Role.DORMANT,
        reason=(
            "A derived output whose inputs are themselves dormant. Four of its "
            "five vulnerability inputs (structural vulnerability, funding "
            "stress, refinancing pressure, leverage excess) have no data, so "
            "it cannot be honestly derived from co-occurrence."
        ),
        blocking_requirement="At least the funding and leverage inputs must become available.",
    ),
    InactiveComponent(
        key="order_flow_market_depth",
        label="Order Flow / Market Depth",
        role=Role.DORMANT,
        reason=(
            "No institutional order flow or depth data exists. Spot FX/XAUUSD "
            "has no consolidated order book. The project does fetch a 'volume' "
            "column from the Yahoo chart endpoint but never uses it in any "
            "calculation, and it must never be labelled institutional flow."
        ),
        blocking_requirement="Genuine futures volume/open interest or exchange depth data.",
    ),
    InactiveComponent(
        key="execution_cost_spread",
        label="Spread / Execution Cost",
        role=Role.DORMANT,
        reason=(
            "The 5-minute Yahoo bars carry no bid/ask, so no real spread or "
            "execution cost is observable. Honestly-labelled proxies (realized "
            "volatility, session window) remain permitted and are not this."
        ),
        blocking_requirement="A broker/venue quote feed with recorded historical spreads.",
    ),
    InactiveComponent(
        key="gold_official_sector_demand",
        label="Gold Official-Sector Demand",
        role=Role.DORMANT,
        reason="Only news keyword proxies exist ('central bank buying'); that is not data.",
        blocking_requirement="An official-sector reserves dataset.",
    ),
    InactiveComponent(
        key="gold_etf_flows",
        label="Gold ETF Flows",
        role=Role.DORMANT,
        reason="Only news keyword proxies exist ('gold etf inflow'); that is not data.",
        blocking_requirement="An ETF holdings/flows dataset.",
    ),
    InactiveComponent(
        key="oil_inventories",
        label="Oil Inventories",
        role=Role.DORMANT,
        reason="Only news keyword proxies exist ('inventory draw'); that is not data.",
        blocking_requirement="An EIA/API inventory series.",
    ),
    InactiveComponent(
        key="opec_supply",
        label="OPEC / Supply Conditions",
        role=Role.DORMANT,
        reason="Only news keyword proxies exist ('supply cut'); that is not data.",
        blocking_requirement="A production/quota dataset.",
    ),
    InactiveComponent(
        key="crude_term_structure",
        label="Crude Term Structure",
        role=Role.DORMANT,
        reason=(
            "The project holds spot crude series only (DCOILWTICO/DCOILBRENTEU). "
            "There is no futures curve, so backwardation and contango -- the "
            "market's own read on physical tightness -- cannot be observed."
        ),
        blocking_requirement="A futures curve or at least a front/second-month spread.",
    ),
    InactiveComponent(
        key="refinery_and_shipping",
        label="Refinery Runs / Shipping Flows",
        role=Role.DORMANT,
        reason="No refinery utilisation, crack spread or freight data exists.",
        blocking_requirement="A refinery/freight dataset.",
    ),
    InactiveComponent(
        key="nasdaq_earnings_revisions",
        label="Nasdaq Earnings / Estimate Revisions",
        role=Role.DORMANT,
        reason=(
            "No earnings, estimate or revision data exists. News coverage of "
            "results is sentiment about earnings, not an earnings dataset, and "
            "is not promoted into this role."
        ),
        blocking_requirement="An estimates/revisions dataset.",
    ),
    InactiveComponent(
        key="equity_liquidity_flows",
        label="Equity Liquidity / Fund Flows",
        role=Role.DORMANT,
        reason="No fund-flow or equity-liquidity series exists in this project.",
        blocking_requirement="A flows dataset.",
    ),
    InactiveComponent(
        key="index_breadth_concentration",
        label="Index Breadth / Concentration",
        role=Role.DORMANT,
        reason=(
            "Only the index level (NASDAQ100) is available. Breadth and megacap "
            "concentration need constituent data, which this project has none of."
        ),
        blocking_requirement="Constituent-level index data.",
    ),
    InactiveComponent(
        key="central_bank_intervention",
        label="FX Intervention",
        role=Role.DORMANT,
        reason="No intervention or reserve-operation data exists.",
        blocking_requirement="An official intervention/reserves dataset.",
    ),
    InactiveComponent(
        key="cross_currency_basis",
        label="Cross-Currency Basis",
        role=Role.DORMANT,
        reason=(
            "No basis-swap data exists. This is funding-market plumbing, which "
            "remains unsupported across the whole architecture."
        ),
        blocking_requirement="A cross-currency basis series.",
    ),
    InactiveComponent(
        key="vintage_macro_data",
        label="Vintage / Revision-Aware Macro Data",
        role=Role.DORMANT,
        reason=(
            "fetch_fred reads the current-vintage FRED endpoint, not ALFRED. "
            "Current values are not what was known historically, so any "
            "historical test built on them carries a revision-leakage bias. "
            "This limitation is declared here so it is visible in output rather "
            "than assumed away."
        ),
        blocking_requirement="ALFRED-style vintage retrieval.",
    ),
)


# ---------------------------------------------------------------------------
# WITHHELD -- code exists in the project, activation is blocked for a reason.
# ---------------------------------------------------------------------------

WITHHELD_COMPONENTS: tuple[InactiveComponent, ...] = (
    InactiveComponent(
        key="macro_thesis_invalidation",
        label="Macro Thesis Invalidation + Escalation",
        role=Role.ACTIVE_NON_VOTING,
        reason=(
            "Implemented in apex.b2.thesis and NOT WIRED. open_thesis, "
            "record_failure, apply_macro_evidence, apply_escalation and "
            "restore_thesis have no callers outside the test suite: no live "
            "evaluation constructs a ThesisRecord, so every shadow record "
            "carries thesis=null and thesis_state=null and the escalation rule "
            "has never run. The lifecycle itself is correct -- price cannot "
            "flip a macro thesis, only macro evidence can invalidate one, and "
            "restoration requires new macro evidence. It is withheld because "
            "the same rule that withholds relative_value_layer applies: "
            "nothing calls it and nothing logs it, so it is not an implemented "
            "feature and must not be counted as one."
        ),
        blocking_requirement=(
            "A persisted per-instrument thesis store, macro family counts fed "
            "into apply_macro_evidence, setup failures recorded from resolved "
            "outcomes -- and the single-instant invalidation edge closed first "
            "(one conflicting family with two unavailable ones currently "
            "satisfies conflicting>0 and supporting==0)."
        ),
    ),
    InactiveComponent(
        key="transmission_regime_confidence_channel",
        label="Transmission-confirmation channel into Regime Confidence",
        role=Role.DIAGNOSTIC,
        reason=(
            "apex.b2.regime accepts a transmission_rate that may only LOWER "
            "regime confidence, and apex.b2.predictions exposes it through "
            "regime_confidence_contribution. The channel is inert: "
            "PredictionLog.attach_outcome has no caller anywhere, so "
            "confirmation_rate() always returns (None, 0), and the live "
            "evaluation path never passes a prediction_log at all. Regime "
            "Confidence itself is active and reaches every record; only this "
            "one input to it is withheld."
        ),
        blocking_requirement=(
            "Correct per-step transmission polarity and a resolver that can "
            "measure a step, then outcome attachment. See "
            "transmission_prediction_registration."
        ),
    ),
    InactiveComponent(
        key="transmission_prediction_registration",
        label="Transmission Prediction Registration",
        role=Role.DIAGNOSTIC,
        reason=(
            "Registration is DISABLED at the pre-freeze boundary. Every step of "
            "every registered chain was stamped with the instrument thesis "
            "direction, so a bullish-gold thesis pre-registered the claims "
            "'real yields rise' and 'USD rises' -- the inverse of the mechanism "
            "the gold module's own rationale states. The chain endpoints are "
            "also free-text with no resolver, so no step was measurable even in "
            "principle. The append-only log structure and its anti-hindsight "
            "guarantees are correct and retained; the chain SEMANTICS are not."
        ),
        blocking_requirement=(
            "Per-step expected polarity relative to the thesis, plus a "
            "measurable observable key per endpoint. The pre-freeze corpus is "
            "marked invalid and must never be resolved or reinterpreted."
        ),
    ),
    InactiveComponent(
        key="scenario_condition_evaluation",
        label="Scenario Invalidation-Condition Evaluation",
        role=Role.DIAGNOSTIC,
        reason=(
            "build_scenario_set writes pre-registered, falsifiable invalidation "
            "conditions onto every record, and that part is active. "
            "evaluate_conditions -- the function that would check whether any of "
            "them has since occurred -- has no caller anywhere. The conditions "
            "are therefore written and never evaluated."
        ),
        blocking_requirement=(
            "A scheduled pass that re-reads stored conditions against later "
            "readings. Registration is already correct; only evaluation is missing."
        ),
    ),
    InactiveComponent(
        key="cross_asset_bridge",
        label="Cross-Asset Bridge",
        role=Role.ACTIVE_NON_VOTING,
        reason=(
            "compute_cross_asset_confirmation exists but all six of its "
            "relationships confirm a thesis using one of that thesis's own "
            "inputs (real yields are 30% of Gold's score, USD macro is 20% of "
            "Gold's and Oil's and 15% of Nasdaq's, oil momentum is 15% of "
            "CAD's, the JPY rate leg is inside JPY's own composite). "
            "Activating it would manufacture confirmation out of re-measured "
            "inputs."
        ),
        blocking_requirement=(
            "A thesis-input registry that programmatically excludes any variable "
            "used to build the thesis from its confirmation set, plus "
            "Stable/Weakening/Broken/Divergence relationship stability with "
            "Broken mapping to Unavailable rather than 'no confirmation'."
        ),
    ),
    InactiveComponent(
        key="relative_value_layer",
        label="FX Relative Value",
        role=Role.ASSET_SPECIFIC_MODULE,
        reason=(
            "compute_relative_value is well-formed and correctly non-voting, "
            "but nothing calls it and nothing logs it, so it is not an "
            "implemented feature. It must not be counted as one."
        ),
        blocking_requirement="Shadow-mode logging (Stage B) plus forward validation.",
    ),
    InactiveComponent(
        key="macro_regime_context",
        label="Macro Regime Context",
        role=Role.META_STATE,
        reason=(
            "compute_macro_regime_context exists but is called by nothing, and "
            "its internal vote counting double-counts real-yield momentum "
            "(directly, and again inside the gold score it also counts). Its "
            "risk_on/risk_off states are also not the Trending/Range/Stress "
            "meta-state B2 specifies."
        ),
        blocking_requirement="Regime State + separate Regime Confidence, without double counting.",
    ),
    InactiveComponent(
        key="recent_macro_surprise",
        label="Recent Macro Surprise Bridge",
        role=Role.DIAGNOSTIC,
        reason="compute_recent_macro_surprise exists but is called by nothing and logged nowhere.",
        blocking_requirement="Shadow-mode logging (Stage B) plus forward validation.",
    ),
    InactiveComponent(
        key="false_signal_whipsaw_detection",
        label="False Signal / Whipsaw Detection",
        role=Role.ACTIVE_NON_VOTING,
        reason=(
            "Not implemented anywhere in this project. It is a pre-entry setup "
            "credibility test ('is this apparent setup likely to be noise?') and "
            "must stay separate from Technical Invalidation, which is a "
            "post-setup failure condition ('what proves this setup is dead?'). "
            "They are different functions at different points in the trade "
            "lifecycle and are not merged here."
        ),
        blocking_requirement="A noise/whipsaw model with its own validation.",
    ),
    InactiveComponent(
        key="gold_pricing_matrix_display_rows",
        label="Gold Pricing Matrix display rows",
        role=Role.DIAGNOSTIC,
        reason=(
            "The Gold page's pricing matrix contains hard-coded display values "
            "for the DGS10 and T10YIE rows. They are presentation placeholders, "
            "not measurements, and must never be read as evidence by any "
            "scoring logic."
        ),
        blocking_requirement="Never. These are display artefacts; B2 must read the source series.",
    ),
)


# ---------------------------------------------------------------------------
# ASSET-SPECIFIC MODULES -- active, non-voting transmission diagnostics.
#
# Every driver in every one of these modules is a TRANSFORMATION of evidence
# that already votes in the universal core, or is dormant for want of data. The
# modules therefore add zero votes and the voting budget is untouched. That is
# the intended outcome: the evidence that would be genuinely independent for
# these instruments (official-sector demand, inventories, positioning,
# earnings) is exactly the data this project does not have.
# ---------------------------------------------------------------------------

ASSET_MODULES: tuple[AssetModuleComponent, ...] = (
    AssetModuleComponent(
        key="gold_module_v1",
        label="Gold transmission module",
        instrument="Gold",
        role=Role.ASSET_SPECIFIC_MODULE,
        rationale=(
            "Three channels -- real-rate, USD and safe-haven/news -- each a "
            "restatement of evidence already voting in Policy / Real Rates, "
            "Macro Activity and News / Geopolitical respectively. Diagnostic "
            "only: it reports whether each channel is transmitting the thesis, "
            "and never adds a vote."
        ),
    ),
    AssetModuleComponent(
        key="oil_module_v1",
        label="Oil transmission module",
        instrument="Oil",
        role=Role.ASSET_SPECIFIC_MODULE,
        rationale=(
            "Three channels -- price/trend, USD and supply narrative -- "
            "restating Directional, Macro Activity and News / Geopolitical "
            "respectively. The supply channel is explicitly a narrative read: "
            "physical inventories, OPEC output, refinery/shipping and term "
            "structure have no data here and stay dormant rather than proxied."
        ),
    ),
    AssetModuleComponent(
        key="fx_module_v1",
        label="FX transmission module",
        instrument="USD,EUR,GBP,CAD,JPY,CHF,AUD,NZD",
        role=Role.ASSET_SPECIFIC_MODULE,
        rationale=(
            "Supplies the relative read the universal core lacks, since "
            "production scores each currency in isolation. Relative macro and "
            "relative policy are differences of quantities that already vote, "
            "and news is the domestic leg only. Exactly one counter currency "
            "per instrument, so one body of evidence cannot surface repeatedly "
            "across several comparisons."
        ),
    ),
    AssetModuleComponent(
        key="nasdaq_module_v1",
        label="Nasdaq transmission module",
        instrument="NDX",
        role=Role.ASSET_SPECIFIC_MODULE,
        rationale=(
            "Three channels -- real-yield duration sensitivity, USD financial "
            "conditions and growth-risk news -- restating Policy / Real Rates, "
            "Macro Activity and News / Geopolitical. Price trend is "
            "deliberately excluded because it already votes through the "
            "Directional family; earnings revisions, liquidity flows and index "
            "breadth are dormant."
        ),
    ),
)


def _validate_registry() -> None:
    """Enforce the budget and the anti-double-counting invariants at import time."""
    if len(VOTING_FAMILIES) > VOTING_BUDGET:
        raise ValueError(
            f"Voting budget exceeded: {len(VOTING_FAMILIES)} families declared, "
            f"budget is {VOTING_BUDGET}. Adding a family must displace one."
        )

    keys = [f.key for f in VOTING_FAMILIES]
    if len(set(keys)) != len(keys):
        raise ValueError("Duplicate voting family keys")

    # Every voting member must declare a scale and a frequency. Enforced here
    # as well as in __post_init__ so the invariant holds for the registry as a
    # whole and not merely one definition at a time.
    for family in VOTING_FAMILIES:
        for spec in family.member_specs:
            if spec.threshold <= 0.0:
                raise ValueError(
                    f"{family.key}.{spec.key}: a neutral band must be positive. "
                    "A zero band makes every non-zero reading directional."
                )
            if spec.scale is MemberScale.STANDARDISED_SIGMA and spec.threshold < 0.1:
                raise ValueError(
                    f"{family.key}.{spec.key}: a standardised-sigma member may not "
                    f"use a neutral band of {spec.threshold} sigma. A band this "
                    "small classifies ordinary noise as directional evidence, "
                    "which is the defect MemberScale was introduced to prevent."
                )

    # A member may belong to exactly one family. This is the structural guard
    # against the same evidence being counted twice under two labels.
    seen: dict[str, str] = {}
    for family in VOTING_FAMILIES:
        for member in family.members:
            if member in seen:
                raise ValueError(
                    f"Member {member!r} appears in both {seen[member]!r} and "
                    f"{family.key!r}; a member may belong to exactly one family."
                )
            seen[member] = family.key

    inactive_keys = [c.key for c in ACTIVE_NON_VOTING_COMPONENTS + DORMANT_COMPONENTS + WITHHELD_COMPONENTS]
    if len(set(inactive_keys)) != len(inactive_keys):
        raise ValueError("Duplicate inactive component keys")

    overlap = set(inactive_keys) & set(keys)
    if overlap:
        raise ValueError(f"Components cannot be both voting and inactive: {sorted(overlap)}")

    for component in DORMANT_COMPONENTS:
        if component.role is not Role.DORMANT:
            raise ValueError(f"{component.key}: dormant components must have role DORMANT")

    if not CRITICAL_FAMILY_KEYS <= set(keys):
        raise ValueError("CRITICAL_FAMILY_KEYS references an undeclared family")

    # H3: an UNOBTAINABLE member is excluded from the coverage denominator
    # forever, so the reason has to be on the record rather than in someone's
    # head. Without this, "unobtainable" becomes a way to quietly delete an
    # inconvenient member from the measure of completeness.
    for family in VOTING_FAMILIES:
        for spec in family.member_specs:
            if (
                spec.expectation is EvidenceExpectation.UNOBTAINABLE
                and not spec.frequency_basis.strip()
            ):
                raise ValueError(
                    f"{family.key}.{spec.key}: a member declared UNOBTAINABLE must "
                    "record why in frequency_basis. It is removed from the Data "
                    "Confidence denominator permanently, and an unexplained "
                    "removal is indistinguishable from hiding a data gap."
                )

    # H3: every canonical macro family must be accounted for somewhere in this
    # registry. A key that is neither voting nor dormant would make the
    # architectural completeness cap silently under-report -- the family would
    # be absent from the system AND absent from the list of things noted as
    # absent, which is the exact failure the cap exists to prevent.
    unaccounted = CANONICAL_MACRO_FAMILY_KEYS - (set(keys) | set(inactive_keys))
    if unaccounted:
        raise ValueError(
            f"CANONICAL_MACRO_FAMILY_KEYS entries {sorted(unaccounted)} are neither "
            "declared as voting families nor registered as inactive components. A "
            "canonical macro family must be visible in the registry either way."
        )

    module_keys = [m.key for m in ASSET_MODULES]
    if len(set(module_keys)) != len(module_keys):
        raise ValueError("Duplicate asset module keys")
    # An asset module must never share an identity with a voting family or with
    # an inactive component: they are different roles with different rules.
    clash = set(module_keys) & (set(keys) | set(inactive_keys))
    if clash:
        raise ValueError(f"Asset modules clash with existing components: {sorted(clash)}")


_validate_registry()


def voting_family_keys() -> tuple[str, ...]:
    return tuple(f.key for f in VOTING_FAMILIES)


def active_non_voting_keys() -> tuple[str, ...]:
    return tuple(c.key for c in ACTIVE_NON_VOTING_COMPONENTS)


def dormant_keys() -> tuple[str, ...]:
    return tuple(c.key for c in DORMANT_COMPONENTS)


def asset_module_keys() -> tuple[str, ...]:
    return tuple(m.key for m in ASSET_MODULES)


def withheld_keys() -> tuple[str, ...]:
    return tuple(c.key for c in WITHHELD_COMPONENTS)


def dormant_canonical_macro_families() -> tuple[str, ...]:
    """Canonical universal macro families that are declared but have no data.

    Computed from the LIVE registry state rather than from a hard-coded count,
    so the H3 architectural completeness cap lifts by itself the moment a
    funding, positioning or issuance source is genuinely activated. Nothing
    needs to remember to remove a constant.

    Sorted, so the value is deterministic and two records built from the same
    registry state serialise identically.
    """
    return tuple(sorted(CANONICAL_MACRO_FAMILY_KEYS & set(dormant_keys())))


#: Bumped when the MEANING of a member spec changes -- a new scale, a new
#: threshold rule, a corrected frequency. Stored on every record so a stored
#: reading stays interpretable if these declarations are ever revised.
MEMBER_SPEC_VERSION = "b2-member-spec-v1"


def member_spec_provenance() -> dict[str, object]:
    """Everything needed to re-derive how each member was classified.

    Recorded on every shadow record. Without it a stored member value cannot be
    re-thresholded later: an analyst would not know which scale the number was
    on, which band was applied, or which horizon rule governed it -- and would
    have to consult repository history to find out.
    """
    return {
        "version": MEMBER_SPEC_VERSION,
        # H3: the expectation declarations that produced this record's coverage
        # denominator. Versioned separately from MEMBER_SPEC_VERSION because a
        # reclassified member changes what Data Confidence MEANS without
        # changing how any member is scaled, thresholded or horizon-checked.
        "expectation_version": EXPECTATION_VERSION,
        "canonical_macro_families": sorted(CANONICAL_MACRO_FAMILY_KEYS),
        "dormant_canonical_macro_families": list(dormant_canonical_macro_families()),
        "scale_thresholds": {
            scale.value: float(threshold)
            for scale, threshold in _DEFAULT_THRESHOLD_BY_SCALE.items()
        },
        "families": {
            family.key: [spec.as_record() for spec in family.member_specs]
            for family in VOTING_FAMILIES
        },
    }


def describe_budget() -> dict[str, object]:
    """Auditable summary of the voting budget and what is deliberately excluded."""
    return {
        "budget": VOTING_BUDGET,
        "declared": len(VOTING_FAMILIES),
        "remaining": VOTING_BUDGET - len(VOTING_FAMILIES),
        "voting": list(voting_family_keys()),
        "macro": sorted(MACRO_FAMILY_KEYS),
        "technical": sorted(TECHNICAL_FAMILY_KEYS),
        "critical": sorted(CRITICAL_FAMILY_KEYS),
        # H3: the canonical macro set and how much of it actually exists here.
        "canonical_macro": sorted(CANONICAL_MACRO_FAMILY_KEYS),
        "dormant_canonical_macro": list(dormant_canonical_macro_families()),
        "active_non_voting": list(active_non_voting_keys()),
        "dormant": list(dormant_keys()),
        "withheld": list(withheld_keys()),
        # Asset modules are listed separately from the voting core precisely
        # because they add no votes to it.
        "asset_modules": list(asset_module_keys()),
    }
